"""Track INSERT + PerformanceData UPDATE — trigger ownership and blob round-trip.

These tests exist because a writer that INSERTs PerformanceData would race the
captured trigger (PK violation / duplicate state), and a writer that silently
re-encodes path/blobs would make playlist + Engine GUI loads fail in ways that
unit-level self-consistency cannot catch. Expected blob payloads are built
from the same writer/blobs encoders the production path uses as inputs, then
decoded from the DB — not generated by re-running insert_tracks and pasting.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest

from rb2engine.ir_engine import (
    EMPTY_LOOP,
    EMPTY_QUICK_CUE,
    EngineBeatGrid,
    EngineBeatMarker,
    EngineTrack,
    LoopSlot,
    QuickCueSlot,
)
from rb2engine.writer import schema as schema_mod
from rb2engine.writer.blobs import (
    BeatData,
    BeatGrid,
    BeatMarker,
    Color,
    Loop,
    Loops,
    QuickCue,
    QuickCues,
    TrackData,
    decode_beat_data,
    decode_loops,
    decode_quick_cues,
    decode_track_data,
    encode_beat_data,
    encode_loops,
    encode_quick_cues,
    encode_track_data,
)
from rb2engine.writer.tracks import insert_tracks

DDL_DIR = Path(__file__).resolve().parents[2] / "src" / "rb2engine" / "writer" / "ddl"
DB_UUID = "11111111-2222-3333-4444-555555555555"

# Hand-authored IR values — not derived from insert_tracks output.
SAMPLE_RATE = 44100.0
SAMPLES = 441_000  # 10.0 s exactly
BPM_INT = 128
BPM_ANALYZED = 128.0
KEY_ORD = 5
PATH_VERBATIM = "../Contents/Artist/Track Name.mp3"
CUE_OFFSET = 22050.0
LOOP_START = 44100.0
LOOP_END = 88200.0
CUE_COLOR = (255, 10, 20, 30)
LOOP_COLOR = (255, 40, 50, 60)


def _empty_slots() -> tuple[list[QuickCueSlot], list[LoopSlot]]:
    return [EMPTY_QUICK_CUE] * 8, [EMPTY_LOOP] * 8


def _make_track(**overrides: object) -> EngineTrack:
    cues, loops = _empty_slots()
    cues = list(cues)
    loops = list(loops)
    cues[0] = QuickCueSlot(
        label="Drop",
        sample_offset=CUE_OFFSET,
        color=CUE_COLOR,
    )
    loops[0] = LoopSlot(
        label="Loop A",
        start_sample_offset=LOOP_START,
        end_sample_offset=LOOP_END,
        is_start_set=1,
        is_end_set=1,
        color=LOOP_COLOR,
    )
    grid = EngineBeatGrid(
        default_markers=[
            EngineBeatMarker(sample_offset=-4000.0, beat_number=-4, number_of_beats=50),
            EngineBeatMarker(sample_offset=float(SAMPLES), beat_number=46, number_of_beats=0),
        ],
        adjusted_markers=[
            EngineBeatMarker(sample_offset=-4000.0, beat_number=-4, number_of_beats=50),
            EngineBeatMarker(sample_offset=float(SAMPLES), beat_number=46, number_of_beats=0),
        ],
        is_beatgrid_set=True,
    )
    fields: dict[str, object] = {
        "path": PATH_VERBATIM,
        "title": "Track Name",
        "artist": "Artist",
        "album": "Album",
        "genre": "House",
        "label": "Label",
        "comment": "a comment",
        "composer": "Composer",
        "year": 2020,
        "track_number": 3,
        "disc_number": 1,
        "bpm": BPM_INT,
        "bpm_analyzed": BPM_ANALYZED,
        "key": KEY_ORD,
        "rating": 100,
        "sample_rate": SAMPLE_RATE,
        "samples": SAMPLES,
        "date_added": 1_700_000_000,
        "date_created": 1_700_000_100,
        "last_edit_time": 1_700_000_200,
        "album_art_hash": None,
        "beat_grid": grid,
        "quick_cues": cues,
        "loops": loops,
    }
    fields.update(overrides)
    return EngineTrack(**fields)  # type: ignore[arg-type]


def _expected_track_data(track: EngineTrack) -> TrackData:
    return TrackData(
        sample_rate=float(track.sample_rate),
        samples=int(track.samples),
        key=int(track.key) if track.key is not None else 0,
    )


def _expected_beat_data(track: EngineTrack) -> BeatData:
    bg = track.beat_grid
    return BeatData(
        sample_rate=float(track.sample_rate),
        samples=float(track.samples),
        is_beatgrid_set=1 if bg.is_beatgrid_set else 0,
        default_beat_grid=BeatGrid(
            markers=[
                BeatMarker(m.sample_offset, m.beat_number, m.number_of_beats, m.unknown)
                for m in bg.default_markers
            ]
        ),
        adjusted_beat_grid=BeatGrid(
            markers=[
                BeatMarker(m.sample_offset, m.beat_number, m.number_of_beats, m.unknown)
                for m in bg.adjusted_markers
            ]
        ),
    )


def _expected_quick_cues(track: EngineTrack) -> QuickCues:
    return QuickCues(
        cues=[
            QuickCue(s.label, s.sample_offset, Color(*s.color)) for s in track.quick_cues
        ]
    )


def _expected_loops(track: EngineTrack) -> Loops:
    return Loops(
        loops=[
            Loop(
                s.label,
                s.start_sample_offset,
                s.end_sample_offset,
                s.is_start_set,
                s.is_end_set,
                Color(*s.color),
            )
            for s in track.loops
        ]
    )


def _create_db(path: Path, schema: tuple[int, int, int]) -> sqlite3.Connection:
    """Open a real DB from captured DDL for the requested schema triple.

    3.0.1 goes through schema.create_database (supported). 3.0.2 DDL is applied
    directly so this suite does not depend on another worker registering it in
    SUPPORTED_SCHEMAS — the column-name-explicit INSERT contract must still hold.
    """
    if schema == (3, 0, 1):
        conn = schema_mod.create_database(path, schema, database_uuid=DB_UUID)
    elif schema == (3, 0, 2):
        ddl_path = DDL_DIR / "schema_3_0_2.sql"
        conn = sqlite3.connect(str(path))
        conn.execute("PRAGMA journal_mode=DELETE")
        conn.executescript(ddl_path.read_text(encoding="utf-8"))
        conn.execute(
            """
            INSERT INTO Information (
                uuid, schemaVersionMajor, schemaVersionMinor, schemaVersionPatch,
                currentPlayedIndiciator, lastRekordBoxLibraryImportReadCounter
            ) VALUES (?, 3, 0, 2, 0, NULL)
            """,
            (DB_UUID,),
        )
        conn.commit()
    else:
        raise AssertionError(f"unexpected schema {schema}")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


@pytest.fixture(params=[(3, 0, 1), (3, 0, 2)], ids=["schema_3_0_1", "schema_3_0_2"])
def conn(tmp_path: Path, request: pytest.FixtureRequest) -> sqlite3.Connection:
    schema = request.param
    db_path = tmp_path / f"m_{schema[0]}_{schema[1]}_{schema[2]}.db"
    connection = _create_db(db_path, schema)
    yield connection
    connection.close()


def test_performance_data_row_exists_without_explicit_insert(
    conn: sqlite3.Connection,
) -> None:
    """Trigger owns PerformanceData creation — INSERT would violate the PK.

    The captured DDL fires trigger_after_insert_Track_insert_performance_data.
    If that trigger is missing or the writer double-inserts, Engine libraries
    corrupt silently (or the write aborts).
    """
    track = _make_track()
    before = conn.execute("SELECT COUNT(*) FROM PerformanceData").fetchone()[0]
    assert before == 0

    id_map = insert_tracks(conn, [track])
    conn.commit()

    assert len(id_map) == 1
    engine_id = next(iter(id_map.values()))
    row = conn.execute(
        "SELECT trackId, trackData, beatData, quickCues, loops, "
        "overviewWaveFormData FROM PerformanceData WHERE trackId = ?",
        (engine_id,),
    ).fetchone()
    assert row is not None
    assert row[0] == engine_id
    # overviewWaveFormData is a deliberate non-goal — leave trigger default (NULL).
    assert row[5] is None


def test_path_stored_verbatim_not_recomputed(conn: sqlite3.Connection) -> None:
    """Track.path is the mapper/paths contract string; rewriting it breaks portable sticks.

    Absolute or differently-based paths would work on one mount and fail the
    moment the stick is plugged into another machine — a class of bug no
    in-process oracle catches if the writer "helpfully" recomputes path.
    """
    track = _make_track(path=PATH_VERBATIM)
    insert_tracks(conn, [track])
    conn.commit()
    stored = conn.execute("SELECT path FROM Track").fetchone()[0]
    assert stored == PATH_VERBATIM


def test_requests_waveform_analysis_without_replacing_beatgrid(
    conn: sqlite3.Connection,
) -> None:
    """Engine should build its waveform while leaving the imported grid intact.

    rb2engine writes beatData but deliberately leaves overviewWaveFormData
    empty. Marking the track analyzed suppresses Engine's waveform pass;
    leaving the grid unlocked lets that pass replace the converted grid.
    """
    insert_tracks(conn, [_make_track()])
    conn.commit()

    is_analyzed, is_beatgrid_locked = conn.execute(
        "SELECT isAnalyzed, isBeatGridLocked FROM Track"
    ).fetchone()

    assert is_analyzed == 0
    assert is_beatgrid_locked == 1


def test_bpm_integer_and_bpm_analyzed_real_both_written(
    conn: sqlite3.Connection,
) -> None:
    """Engine stores both columns; writing only one leaves the other stale/NULL."""
    track = _make_track(bpm=BPM_INT, bpm_analyzed=BPM_ANALYZED)
    insert_tracks(conn, [track])
    conn.commit()
    bpm, bpm_analyzed = conn.execute(
        "SELECT bpm, bpmAnalyzed FROM Track"
    ).fetchone()
    assert bpm == BPM_INT
    assert isinstance(bpm, int) or bpm == BPM_INT
    assert bpm_analyzed == pytest.approx(BPM_ANALYZED)


def test_origin_fields_filled_consistently_by_trigger_or_writer(
    conn: sqlite3.Connection,
) -> None:
    """originDatabaseUuid/originTrackId must land non-empty for uniqueness + history.

    Leaving both NULL after insert would mean the fix_origin trigger did not
    fire (DDL incomplete) or the writer overwrote them with empties — either
    way play-history origin links and the UNIQUE constraint fail.
    """
    insert_tracks(conn, [_make_track()])
    conn.commit()
    origin_uuid, origin_id, track_id = conn.execute(
        "SELECT originDatabaseUuid, originTrackId, id FROM Track"
    ).fetchone()
    info_uuid = conn.execute("SELECT uuid FROM Information").fetchone()[0]
    assert origin_uuid == info_uuid == DB_UUID
    assert origin_id == track_id
    assert origin_id is not None and origin_id != 0


def test_decoded_blobs_match_encoded_ir_payloads(conn: sqlite3.Connection) -> None:
    """PerformanceData blobs must round-trip the mapped IR through writer/blobs.

    If insert_tracks invents a parallel encoder or mangles field types, cues and
    grids read back wrong even when the SQLite row "looks fine". Expected values
    come from encode_* of the hand-authored IR, not from re-invoking insert_tracks.
    """
    track = _make_track()
    id_map = insert_tracks(conn, [track])
    conn.commit()
    engine_id = next(iter(id_map.values()))

    row = conn.execute(
        "SELECT trackData, beatData, quickCues, loops FROM PerformanceData "
        "WHERE trackId = ?",
        (engine_id,),
    ).fetchone()
    assert row is not None
    track_blob, beat_blob, cues_blob, loops_blob = row

    # Non-empty blobs (not the zero-length sentinel).
    assert track_blob and beat_blob and cues_blob and loops_blob

    assert decode_track_data(track_blob) == _expected_track_data(track)
    got_beat = decode_beat_data(beat_blob)
    exp_beat = _expected_beat_data(track)
    assert got_beat.sample_rate == exp_beat.sample_rate
    assert got_beat.samples == exp_beat.samples
    assert got_beat.is_beatgrid_set == exp_beat.is_beatgrid_set
    assert got_beat.default_beat_grid.markers == exp_beat.default_beat_grid.markers
    assert got_beat.adjusted_beat_grid.markers == exp_beat.adjusted_beat_grid.markers

    # Byte-identity against the same encoder inputs production must use.
    assert track_blob == encode_track_data(_expected_track_data(track))
    assert beat_blob == encode_beat_data(_expected_beat_data(track))
    assert cues_blob == encode_quick_cues(_expected_quick_cues(track))
    assert loops_blob == encode_loops(_expected_loops(track))

    got_cues = decode_quick_cues(cues_blob)
    assert got_cues.cues[0].label == "Drop"
    assert got_cues.cues[0].sample_offset == CUE_OFFSET
    assert (got_cues.cues[0].color.a, got_cues.cues[0].color.r,
            got_cues.cues[0].color.g, got_cues.cues[0].color.b) == CUE_COLOR

    got_loops = decode_loops(loops_blob)
    assert got_loops.loops[0].label == "Loop A"
    assert got_loops.loops[0].start_sample_offset == LOOP_START
    assert got_loops.loops[0].end_sample_offset == LOOP_END


def test_album_art_id_and_uri_when_art_ids_provided(
    conn: sqlite3.Connection,
) -> None:
    """albumArtId FK + albumArt URI must both be set when art is linked.

    Engine's golden export populates both; writing only the integer id is the
    obvious way to get blank covers despite a correct AlbumArt table. Whether
    Engine *requires* the URI is unverified — we still replicate the shape.
    """
    conn.execute(
        "INSERT INTO AlbumArt (hash, albumArt) VALUES (?, ?)",
        ("abc123", b"\x89PNG_fake"),
    )
    art_id = conn.execute("SELECT id FROM AlbumArt").fetchone()[0]
    conn.commit()

    track = _make_track(album_art_hash="abc123")
    insert_tracks(conn, [track], art_ids={"abc123": art_id})
    conn.commit()

    album_art_id, album_art = conn.execute(
        "SELECT albumArtId, albumArt FROM Track"
    ).fetchone()
    assert album_art_id == art_id
    assert album_art == "image://planck/0"
    # FK resolves under foreign_keys=ON.
    resolved = conn.execute(
        "SELECT id FROM AlbumArt WHERE id = ?", (album_art_id,)
    ).fetchone()
    assert resolved is not None


def test_null_artwork_when_no_hash_or_art_ids(conn: sqlite3.Connection) -> None:
    """Tracks without art must not dangle a bogus albumArtId under ON DELETE RESTRICT."""
    insert_tracks(conn, [_make_track(album_art_hash=None)])
    conn.commit()
    album_art_id, album_art = conn.execute(
        "SELECT albumArtId, albumArt FROM Track"
    ).fetchone()
    assert album_art_id is None
    assert album_art is None


def test_scalar_metadata_written(conn: sqlite3.Connection) -> None:
    """Core catalog columns must match the EngineTrack the mapper handed us."""
    track = _make_track()
    insert_tracks(conn, [track])
    conn.commit()
    row = conn.execute(
        "SELECT title, artist, album, genre, label, comment, composer, "
        "year, key, rating, filename, length, bpm, bpmAnalyzed "
        "FROM Track"
    ).fetchone()
    assert row[0] == "Track Name"
    assert row[1] == "Artist"
    assert row[2] == "Album"
    assert row[3] == "House"
    assert row[4] == "Label"
    assert row[5] == "a comment"
    assert row[6] == "Composer"
    assert row[7] == 2020
    assert row[8] == KEY_ORD
    assert row[9] == 100
    assert row[10] == "Track Name.mp3"
    assert row[11] == 10  # length seconds from samples/sample_rate
    assert row[12] == BPM_INT
    assert row[13] == pytest.approx(BPM_ANALYZED)


def test_never_inserts_performance_data_directly(conn: sqlite3.Connection) -> None:
    """Guard: writer must only UPDATE PerformanceData; the trigger owns INSERT.

    A second INSERT would violate trackId PK. We pin the UPDATE helper's SQL
    (no INSERT) and assert a 1:1 Track↔PerformanceData cardinality with blobs
    filled — trigger-only would leave trackData NULL; double-insert would raise.
    """
    import inspect

    import rb2engine.writer.tracks as tracks_mod

    update_src = inspect.getsource(tracks_mod._update_performance_data)
    assert "UPDATE PerformanceData" in update_src
    # The UPDATE helper must not contain an INSERT statement.
    body_sql = [
        ln
        for ln in update_src.splitlines()
        if "INSERT" in ln.upper() and not ln.strip().startswith(("#", '"""', "'''"))
    ]
    assert body_sql == [], f"UPDATE helper must not INSERT: {body_sql}"

    insert_tracks(
        conn,
        [
            _make_track(),
            _make_track(path="../Contents/Artist/Other.mp3"),
        ],
    )
    conn.commit()
    n_tracks = conn.execute("SELECT COUNT(*) FROM Track").fetchone()[0]
    n_pd = conn.execute("SELECT COUNT(*) FROM PerformanceData").fetchone()[0]
    assert n_tracks == n_pd == 2
    nulls = conn.execute(
        "SELECT COUNT(*) FROM PerformanceData WHERE trackData IS NULL"
    ).fetchone()[0]
    assert nulls == 0


def test_key_none_writes_null_track_key_and_zero_blob_key(
    conn: sqlite3.Connection,
) -> None:
    """Unknown key → Track.key NULL (no guess) but trackData key ordinal 0."""
    track = _make_track(key=None)
    insert_tracks(conn, [track])
    conn.commit()
    key = conn.execute("SELECT key FROM Track").fetchone()[0]
    assert key is None
    blob = conn.execute("SELECT trackData FROM PerformanceData").fetchone()[0]
    assert decode_track_data(blob).key == 0


def test_schema_3_0_2_insert_does_not_require_album_art_source_hash(
    tmp_path: Path,
) -> None:
    """Column-name-explicit INSERT must work when albumArtSourceHash exists but is unused.

    A positional INSERT sized for 3.0.1 would misalign on 3.0.2's extra column.
    """
    conn = _create_db(tmp_path / "m302.db", (3, 0, 2))
    try:
        cols = [r[1] for r in conn.execute("PRAGMA table_info(Track)")]
        assert "albumArtSourceHash" in cols
        insert_tracks(conn, [_make_track()])
        conn.commit()
        assert conn.execute("SELECT COUNT(*) FROM Track").fetchone()[0] == 1
        # Left at default/NULL — we do not invent a source hash.
        assert (
            conn.execute("SELECT albumArtSourceHash FROM Track").fetchone()[0] is None
        )
    finally:
        conn.close()
